package py.com.logixone.plugins.sales.application;

public enum SalesResultCode {
    SUCCESS, ACCESS_DENIED, NOT_FOUND, REFERENCE_CONFLICT, VERSION_CONFLICT,
    IDEMPOTENCY_CONFLICT, DUPLICATE, INVALID_OPERATION, INVENTORY_FAILURE,
    STORAGE_FAILURE
}
