#!/bin/sh

set -eu

archive=''
destination=''

while [ "$#" -gt 0 ]; do
    case "$1" in
        -q)
            shift
            ;;
        -d)
            if [ "$#" -lt 2 ]; then
                echo 'unzip-with-jar: -d requires a destination' >&2
                exit 2
            fi
            destination=$2
            shift 2
            ;;
        --)
            shift
            ;;
        -*)
            echo "unzip-with-jar: unsupported option: $1" >&2
            exit 2
            ;;
        *)
            if [ -n "$archive" ]; then
                echo 'unzip-with-jar: exactly one archive is supported' >&2
                exit 2
            fi
            archive=$1
            shift
            ;;
    esac
done

if [ -z "$archive" ] || [ -z "$destination" ]; then
    echo 'usage: unzip [-q] <archive> -d <destination>' >&2
    exit 2
fi

case "$archive" in
    /*) ;;
    *) archive="$(pwd)/$archive" ;;
esac

mkdir -p "$destination"
cd "$destination"
jar xf "$archive"

find . -type f \( \
    -path '*/bin/mvn' -o \
    -path '*/bin/mvnDebug' -o \
    -path '*/bin/mvnyjp' \
\) -exec chmod 0755 {} +
