package py.com.logixone.plugins.sales.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.*;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.*; import java.util.function.Function;
import org.flywaydb.core.Flyway; import org.junit.jupiter.api.*; import org.testcontainers.junit.jupiter.*; import org.testcontainers.postgresql.PostgreSQLContainer; import org.testcontainers.utility.DockerImageName;
import py.com.logixone.kernel.api.company.CompanyId; import py.com.logixone.kernel.api.security.AppUserId; import py.com.logixone.plugins.businesspartners.api.BusinessPartnerId; import py.com.logixone.plugins.commercialcatalog.api.CatalogItemId; import py.com.logixone.plugins.inventory.api.StockReservationId; import py.com.logixone.plugins.referencedata.api.CurrencyCode; import py.com.logixone.plugins.sales.api.*; import py.com.logixone.plugins.sales.domain.*;
import py.com.logixone.plugins.sales.application.port.SalesOperationRecord; import py.com.logixone.plugins.sales.application.port.SalesTransitionRecord;

@Testcontainers
class SalesPersistencePostgreSqlIT {
 private static final DockerImageName IMAGE=DockerImageName.parse("postgres:18.4-bookworm@sha256:16fa100a3a6e92c0556632870455e7f8c6f3df5cefddd67d6b95292732bd7ff0").asCompatibleSubstituteFor("postgres");
 @Container static final PostgreSQLContainer POSTGRES=new PostgreSQLContainer(IMAGE).withDatabaseName("logixone_sales_test").withUsername("logixone_test").withPassword("test-only-password");
 static EntityManagerFactory factory;
 @BeforeAll static void migrate(){var flyway=Flyway.configure().dataSource(POSTGRES.getJdbcUrl(),POSTGRES.getUsername(),POSTGRES.getPassword()).schemas("plg_sales").defaultSchema("plg_sales").locations("classpath:db/migration/sales").createSchemas(true).cleanDisabled(true).load();assertEquals(1,flyway.migrate().migrationsExecuted);assertEquals(0,flyway.migrate().migrationsExecuted);flyway.validate();factory=Persistence.createEntityManagerFactory(SalesPersistenceNames.TEST_UNIT_NAME,Map.of("jakarta.persistence.jdbc.url",POSTGRES.getJdbcUrl(),"jakarta.persistence.jdbc.user",POSTGRES.getUsername(),"jakarta.persistence.jdbc.password",POSTGRES.getPassword(),"jakarta.persistence.jdbc.driver","org.postgresql.Driver"));}
 @AfterAll static void close(){if(factory!=null)factory.close();}
 @Test void migratesEightPrivateTablesAndValidatesJpa(){assertEquals(8,scalar("SELECT count(*) FROM information_schema.tables WHERE table_schema='plg_sales' AND table_name<>'flyway_schema_history'"));assertDoesNotThrow(()->factory.createEntityManager().close());}
 @Test void persistsCompanyScopedTermsQuotesOrdersAndReservations(){var f=new Fixture();inTx(em->{new JpaSalesTermRepository(em).insert(f.term);new JpaSalesQuoteRepository(em).insert(f.quote);return null;});inTx(em->{f.quote.issue(f.user,Instant.parse("2026-08-20T12:00:00Z"),0);new JpaSalesQuoteRepository(em).update(f.quote,0);return null;});inTx(em->{f.quote.accept(f.user,Instant.parse("2026-08-21T12:00:00Z"),1);new JpaSalesQuoteRepository(em).update(f.quote,1);return null;});var order=SalesOrder.fromQuote(f.company,new SalesOrderId(UUID.randomUUID()),"PED-1",f.quote,f.customer,f.currency,f.term.documentSnapshot());inTx(em->{new JpaSalesOrderRepository(em).insert(order);return null;});var reservation=new StockReservationId(UUID.randomUUID());inTx(em->{order.confirm(Map.of(f.line.id(),reservation),f.user,Instant.now(),0);new JpaSalesOrderRepository(em).update(order,0);return null;});inTx(em->{var stored=new JpaSalesOrderRepository(em).findById(f.company,order.reference().id()).orElseThrow();assertEquals(Map.of(f.line.id(),reservation),stored.reservations());assertTrue(new JpaSalesOrderRepository(em).findById(new CompanyId(UUID.randomUUID()),order.reference().id()).isEmpty());return null;});}
 @Test void persistsCompanyScopedIdempotencyAndAppendOnlyTransitionHistory(){var company=new CompanyId(UUID.randomUUID());var actor=new AppUserId(UUID.randomUUID());var aggregateId=UUID.randomUUID();var occurredAt=Instant.parse("2026-08-21T15:00:00Z");var operation=new SalesOperationRecord(company,"confirm-order-1","CONFIRM_ORDER","a".repeat(64),"ORDER",aggregateId,occurredAt);var transition=new SalesTransitionRecord(company,UUID.randomUUID(),"ORDER",aggregateId,"DRAFT","CONFIRMED",actor,Optional.of("Stock reserved"),occurredAt,"confirm-order-1");inTx(em->{new JpaSalesOperationRepository(em).append(operation);new JpaSalesTransitionRepository(em).append(transition);return null;});inTx(em->{assertEquals(operation,new JpaSalesOperationRepository(em).find(company,"confirm-order-1").orElseThrow());assertTrue(new JpaSalesOperationRepository(em).find(new CompanyId(UUID.randomUUID()),"confirm-order-1").isEmpty());return null;});assertEquals(1,scalar("SELECT count(*) FROM plg_sales.sales_transition_history WHERE aggregate_id='"+aggregateId+"'"));}
 static int scalar(String sql){var em=factory.createEntityManager();try{return ((Number)em.createNativeQuery(sql).getSingleResult()).intValue();}finally{em.close();}}
 static <T>T inTx(Function<EntityManager,T> operation){var em=factory.createEntityManager();try{em.getTransaction().begin();var value=operation.apply(em);em.getTransaction().commit();return value;}catch(RuntimeException x){if(em.getTransaction().isActive())em.getTransaction().rollback();throw x;}finally{em.close();}}
 static final class Fixture {final CompanyId company=new CompanyId(UUID.randomUUID());final AppUserId user=new AppUserId(UUID.randomUUID());final CustomerSnapshot customer=new CustomerSnapshot(new BusinessPartnerId(UUID.randomUUID()),"CLI-1","Cliente","80000000-0",1);final CurrencySnapshot currency=new CurrencySnapshot(new CurrencyCode("PYG"),0,"Guaraní","ISO-2026");final SalesTerm term=SalesTerm.active(company,UUID.randomUUID(),"CONTADO","Contado",0);final SalesLineSnapshot line=new SalesLineSnapshot(UUID.randomUUID(),new CatalogItemId(UUID.randomUUID()),"ITEM-1","Artículo","UN",true,new BigDecimal("2"),new BigDecimal("100"),"IVA10",Optional.of("LP-1"),false,Optional.empty(),1);final SalesQuote quote=SalesQuote.draft(company,new SalesQuoteId(UUID.randomUUID()),"COT-1",customer,currency,term.documentSnapshot(),LocalDate.of(2026,8,31),List.of(line));}
}
