package py.com.logixone.kernel.domain.plugin;

public enum PluginDiagnosticCode {
    DUPLICATE_PLUGIN_ID,
    INCOMPATIBLE_PLUGIN_API,
    DUPLICATE_DEPENDENCY,
    SELF_DEPENDENCY,
    MISSING_REQUIRED_DEPENDENCY,
    INCOMPATIBLE_DEPENDENCY_VERSION,
    FUNCTIONAL_DEPENDS_ON_CUSTOMIZATION,
    CUSTOMIZATION_DEPENDS_ON_CUSTOMIZATION,
    DUPLICATE_CAPABILITY,
    DUPLICATE_PERMISSION,
    DUPLICATE_MENU_CONTRIBUTION,
    DUPLICATE_MIGRATION,
    INVALID_MIGRATION_SCHEMA,
    DUPLICATE_SCREEN_DEFINITION,
    DUPLICATE_SCREEN_ELEMENT,
    DUPLICATE_SCREEN_SLOT,
    INVALID_SCREEN_OWNER,
    SCREEN_DEFINITION_REQUIRES_FUNCTIONAL_PLUGIN,
    DUPLICATE_SCREEN_OVERLAY,
    SCREEN_OVERLAY_REQUIRES_CUSTOMIZATION_PLUGIN,
    SCREEN_OVERLAY_REQUIRES_TARGET_DEPENDENCY,
    CYCLIC_DEPENDENCY
}
