<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>py.com.logixone</groupId>
        <artifactId>logixone-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>web-shell</artifactId>
    <packaging>jar</packaging>

    <name>Smart ERP Web Shell</name>

    <dependencies>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>kernel-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>plugin-api</artifactId>
        </dependency>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>kernel-application</artifactId>
        </dependency>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>kernel-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>business-partners</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>commercial-catalog</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>inventory</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>purchasing</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>py.com.logixone</groupId>
            <artifactId>reference-data</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
