package py.com.logixone.kernel.application.security.port;

public enum SecurityPersistenceCode {
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    EXTERNAL_IDENTITY_ALREADY_EXISTS,
    USER_VERSION_CONFLICT,
    COMPANY_NOT_FOUND,
    MEMBERSHIP_NOT_FOUND,
    MEMBERSHIP_ALREADY_EXISTS,
    MEMBERSHIP_VERSION_CONFLICT,
    ROLE_NOT_FOUND,
    ROLE_ALREADY_EXISTS,
    ROLE_CODE_ALREADY_EXISTS,
    ROLE_VERSION_CONFLICT,
    ROLE_COMPANY_MISMATCH,
    ASSIGNMENT_ALREADY_EXISTS,
    PERMISSION_GRANT_ALREADY_EXISTS,
    SYSTEM_ROLE_NOT_FOUND,
    SYSTEM_ROLE_ALREADY_EXISTS,
    SYSTEM_ROLE_CODE_ALREADY_EXISTS,
    SYSTEM_ROLE_VERSION_CONFLICT,
    SYSTEM_ASSIGNMENT_ALREADY_EXISTS,
    SYSTEM_PERMISSION_GRANT_ALREADY_EXISTS,
    PERSISTENCE_CONFLICT
}
