package py.com.logixone.plugins.sales.infrastructure.persistence;

import jakarta.enterprise.context.ApplicationScoped; import jakarta.persistence.*; import jakarta.transaction.Transactional;
import java.util.*; import java.util.stream.Collectors; import py.com.logixone.kernel.api.company.CompanyId; import py.com.logixone.plugins.inventory.api.StockReservationId; import py.com.logixone.plugins.sales.api.*; import py.com.logixone.plugins.sales.application.port.*; import py.com.logixone.plugins.sales.domain.*;

@ApplicationScoped @Transactional
public class JpaSalesOrderRepository implements SalesOrderRepository {
 @PersistenceContext(unitName=SalesPersistenceNames.UNIT_NAME) EntityManager em;
 public JpaSalesOrderRepository(){} JpaSalesOrderRepository(EntityManager em){this.em=Objects.requireNonNull(em);}
 public Optional<SalesOrder> findById(CompanyId companyId,SalesOrderId id){return Optional.ofNullable(em.find(SalesOrderEntity.class,new SalesOrderEntity.Key(companyId.value(),id.value()))).map(this::restore);}
 public Optional<SalesOrder> findByNumber(CompanyId companyId,String number){return em.createQuery("SELECT o FROM SalesOrderEntity o WHERE o.companyId=:company AND o.number=:number",SalesOrderEntity.class).setParameter("company",companyId.value()).setParameter("number",number).getResultStream().findFirst().map(this::restore);}
 public SalesOrder insert(SalesOrder order){var s=order.snapshot();if(s.state()!=SalesOrderState.DRAFT||!s.reservations().isEmpty())throw new SalesPersistenceException(SalesPersistenceCode.IMMUTABLE_DOCUMENT);try{em.persist(SalesOrderEntity.from(s));for(int i=0;i<s.lines().size();i++)em.persist(SalesOrderLineEntity.from(s.companyId().value(),s.id().value(),i+1,s.lines().get(i)));em.flush();return order;}catch(RuntimeException x){throw SalesConflictMapper.map(x);}}
 public SalesOrder update(SalesOrder order,long expected){var target=order.snapshot();var entity=require(target.companyId().value(),target.id().value(),expected,target.version());var current=restore(entity).snapshot();if(!immutable(current,target)||!target.reservations().entrySet().containsAll(current.reservations().entrySet()))throw new SalesPersistenceException(SalesPersistenceCode.IMMUTABLE_DOCUMENT);try{for(var entry:target.reservations().entrySet())if(!current.reservations().containsKey(entry.getKey()))em.persist(SalesOrderReservationEntity.from(target.companyId().value(),target.id().value(),entry.getKey(),entry.getValue()));entity.apply(target);em.flush();return order;}catch(RuntimeException x){throw SalesConflictMapper.map(x);}}
 private SalesOrderEntity require(UUID c,UUID id,long expected,long domainVersion){if(expected<0||domainVersion!=expected+1)throw new SalesPersistenceException(SalesPersistenceCode.VERSION_CONFLICT);var e=em.find(SalesOrderEntity.class,new SalesOrderEntity.Key(c,id));if(e==null)throw new SalesPersistenceException(SalesPersistenceCode.NOT_FOUND);if(e.version()!=expected)throw new SalesPersistenceException(SalesPersistenceCode.VERSION_CONFLICT);return e;}
 private SalesOrder restore(SalesOrderEntity e){return SalesOrder.restore(e.snapshot(lines(e.companyId(),e.id()),reservations(e.companyId(),e.id())));}
 private List<SalesLineSnapshot> lines(UUID c,UUID id){return em.createQuery("SELECT l FROM SalesOrderLineEntity l WHERE l.companyId=:company AND l.orderId=:id ORDER BY l.position",SalesOrderLineEntity.class).setParameter("company",c).setParameter("id",id).getResultList().stream().map(SalesOrderLineEntity::snapshot).toList();}
 private Map<UUID,StockReservationId> reservations(UUID c,UUID id){return em.createQuery("SELECT r FROM SalesOrderReservationEntity r WHERE r.companyId=:company AND r.orderId=:id",SalesOrderReservationEntity.class).setParameter("company",c).setParameter("id",id).getResultList().stream().collect(Collectors.toUnmodifiableMap(SalesOrderReservationEntity::lineId,SalesOrderReservationEntity::reservation));}
 private static boolean immutable(SalesOrder.Snapshot a,SalesOrder.Snapshot b){return a.number().equals(b.number())&&a.customer().equals(b.customer())&&a.currency().equals(b.currency())&&a.term().equals(b.term())&&a.sourceQuoteId().equals(b.sourceQuoteId())&&a.lines().equals(b.lines());}
}
