package py.com.logixone.kernel.domain.company;

public enum CompanyPluginDiagnosticCode {
    COMPANY_NOT_FOUND,
    COMPANY_INACTIVE,
    COMPANY_VERSION_CONFLICT,
    PLUGIN_NOT_PRESENT,
    PLUGIN_NOT_FUNCTIONAL,
    PLUGIN_DISABLED,
    REQUIRED_DEPENDENCY_NOT_EFFECTIVE,
    ACTIVE_DEPENDENT_EXISTS,
    CUSTOMIZATION_REQUIRED,
    CUSTOMIZATION_NOT_PRESENT,
    CUSTOMIZATION_WRONG_KIND,
    CUSTOMIZATION_ALREADY_ASSIGNED,
    CUSTOMIZATION_INCOMPATIBLE,
    CUSTOMIZATION_CONTRACT_INVALID,
    CUSTOMIZATION_VERSION_CONFLICT
}
